### PR TITLE
Add 12 new emojis

### PR DESCRIPTION
**Pull request by ddededodediamante**

### CODE REVIEW

**Comment by JeremyGamer13** [comment]
sizes are inconsistent, should be 256x256 for all emojis
also the style of the people should be consistent with the face emojis

**Comment by ddededodediamante** [comment]
ill try to make it consister and ill resize images

**Comment by ddededodediamante** [comment]
there

**Comment by ddededodediamante** [comment]
ermm no i made them

**Comment by JeremyGamer13** [comment]
some of these do seem a bit too similar tho, maybe just like changing colors or shapes & stuff would make them more unique

**Comment by ddededodediamante** [comment]
ook tell me what those are

**Comment by JeremyGamer13** [comment]
mainly the arrows, bell, charts, and laptop
the laptop can be restyled to the pm one, and it would be nice if the "person" emojis were in maybe a more exaggerated pose

**Comment by ddededodediamante** [comment]
okay

**Comment by RedMan13** [comment]
> and it would be nice if the "person" emojis were in maybe a more exaggerated pose

whaaat doss that mean :speaking_head:

**Comment by ddededodediamante** [comment]
tell meeee if its oook

**Comment by ddededodediamante** [comment]
o wait i think i forgot resize

**Pull request merged**
