### PR TITLE
penguin sound

### PR DESCRIPTION
**Pull request by KernelTech11**
can i put da penguin sound

### CODE REVIEW

**Comment by KernelTech11** [comment]
@JeremyGamer13

**Comment by JeremyGamer13** [comment]
where did you get this sound from?

**Comment by KernelTech11** [comment]
> where did you get this sound from?

i inspected the google penguin sound and downloaded the sound

**Comment by KernelTech11** [comment]
> did you check the license?

no why

**Comment by KernelTech11** [comment]
> because it can be illegal to use depending on the license???

uhhhhhhhhhh its not licensed??

**Comment by JeremyGamer13** [comment]
what license, also provide url pls if possible

**Comment by KernelTech11** [comment]
> what license, also provide url pls if possible

here https://www.google.com/logos/fnbx/animal_sounds/penguin.mp3

**Comment by KernelTech11** [comment]
any reply?

**Comment by RedMan13** [comment]
uhhhhh :bleh:

**Comment by KernelTech11** [comment]
:thinking:

**Comment by JeremyGamer13** [comment]
sound seems to have no license so we cant really use it

**Comment by KernelTech11** [comment]
> sound seems to have no license so we cant really use it

what about this http://www.vogelstimmen.info/Vogelstimmen_GRATIS/Eselspinguin_Pygoscelis_papua_AMPLE-814752D.mp3

**Comment by KernelTech11** [comment]
wheres reply.:trollface:

**Comment by KernelTech11** [comment]
a y reply

**Comment by KernelTech11** [comment]
ok then

**Pull request closed without merging**
