### PR TITLE
add backdrop ducks.jpg

### PR DESCRIPTION
**Pull request by webbrowser11**
tell me if i'm missing something this is my first time.

### CODE REVIEW

**Comment by JeremyGamer13** [comment]
picture should be 960x720 (you might need to crop part of it)

**Comment by webbrowser11** [comment]
thanks.

**Comment by webbrowser11** [comment]
updated the size.

**Comment by JeremyGamer13** [comment]
this is your picture right?

**Comment by webbrowser11** [comment]
yes im a dev and photographer...

**Comment by JeremyGamer13** [comment]
alright, adding stuff to this repo doesnt add it directly into the backdrop picker but i can do that

**Comment by webbrowser11** [comment]
wait for the future is that in the main repo and how do i do that?

**Comment by JeremyGamer13** [comment]
its in the penguinmod.github.io repo, like this:
https://github.com/PenguinMod/penguinmod.github.io/commit/89e6e41458b5182746936555153e52bd86f824ae#diff-f5212a6f4293788a48500e688df2f42ae1d6a4b92fc16f21d039e297f67b5878

**Comment by webbrowser11** [comment]
dang im really bad at javascript but ill try next time

**Pull request merged**
