### PR TITLE
add loud, sound, speaker, muted and tada emojis

### PR DESCRIPTION
**Pull request by ddededodediamante**
so new emojis

### CODE REVIEW

**Comment by JeremyGamer13** [comment]
these seem to be in the wrong folder
if you want the emojis to be usable by the site then put them in `files/emojis`

**Comment by ddededodediamante** [comment]
oh i thought they belonged here, because there's just index.html in there

**Comment by JeremyGamer13** [comment]
yea the folder named "files" is where everything actually goes, but the root "emojis" folder is just so the website has an emojis page

**Comment by ddededodediamante** [comment]
i forgot to remove them from assets but idk if that will do smth

**Comment by JeremyGamer13** [comment]
should be fine

**Comment by ddededodediamante** [comment]
ok, thanks for merging

**Pull request merged**
