### PR TITLE
circle guy from the hit mod circle ide

### PR DESCRIPTION
**Pull request by Rubiidev-18**
**new sprite** for _pm_! 
_**(ye text is ugly replace it with Circle IDE)**_

### CODE REVIEW

**Comment by JeremyGamer13** [comment]
if this is a mascot for something then you probably dont want to submit it here
submitting something here means that you allow anyone to use it (even when money is involved) without crediting you

**Comment by Rubiidev-18** [comment]
> if this is a mascot for something then you probably dont want to submit it here submitting something here means that you allow anyone to use it (even when money is involved) without crediting you

#circleguyforpenguinmod

(yea check my pm acc for an edited version WITH a watermark.)

**Comment by JeremyGamer13** [comment]
i dont know your pm account? watermarks go against the whole "free to use" thing too

**Comment by JeremyGamer13** [comment]
you probably shouldnt submit here if you dont like that

**Comment by Rubiidev-18** [comment]
> i dont know your pm account? watermarks go against the whole "free to use" thing too

https://penguinmod.com/profile?user=---firefoxgamer4---

**Comment by Rubiidev-18** [comment]
> you probably shouldnt submit here if you dont like that

also I updated the cgfpm project because like I still want it to be a mod mascot, but like not for people using the sprite.

**Comment by Rubiidev-18** [comment]
No activity.

**Comment by RedMan13** [comment]
boowomp

**Pull request closed without merging**
