### PR TITLE
add Joe!!!!!!!!!!!!!!!!!!!

### PR DESCRIPTION
**Pull request by PuzzlingGGG**
from joe simulator!!!!!!!!!!!!

### CODE REVIEW

**Review by JeremyGamer13 — CHANGES_REQUESTED** [review]
remove the text since its english-only (so untranslatable) and also has profanity

**Comment by JeremyGamer13** [comment]
erm me waiting for joe update.... :trollface:

**Review by JeremyGamer13 — APPROVED** [review]
mmyea are you fine with this being public domain
https://creativecommons.org/public-domain/cc0/

**Comment by PuzzlingGGG** [comment]
ye si m

**Comment by JeremyGamer13** [comment]
will add to library later cuz thats manual not automatical

**Comment by PuzzlingGGG** [comment]
ohj

**Pull request merged**
