### PR TITLE
add cool sounds

### PR DESCRIPTION
**Pull request by qbjl**
most of these come from [here](https://taira-komori.jpn.org/freesounden.html) or Scratch 🍡

### CODE REVIEW

**Comment by RedMan13** [comment]
@JeremyGamer13

**Review by JeremyGamer13 — CHANGES_REQUESTED** [review]
image
your provided source has some rules that mean we cant use the sound effects added here

**Review by JeremyGamer13 — CHANGES_REQUESTED** [review]
image
some of these files are not .mp3 format but are .wav

**Comment by JeremyGamer13** [comment]
ignore .wav format request

**Pull request closed without merging**
